var searchData=
[
  ['raster_19310',['Raster',['../classug_1_1_raster.html',1,'ug']]],
  ['rasterlayerdesc_19311',['RasterLayerDesc',['../structug_1_1_raster_layer_desc.html',1,'ug']]],
  ['rasterlayers_19312',['RasterLayers',['../classug_1_1_raster_layers.html',1,'ug']]],
  ['rasterlayersprojector_19313',['RasterLayersProjector',['../classug_1_1_raster_layers_projector.html',1,'ug']]],
  ['rasteruserdata_19314',['RasterUserData',['../classug_1_1_raster_user_data.html',1,'ug']]],
  ['rawuserdatawrapper_19315',['RawUserDataWrapper',['../structug_1_1bridge_1_1lua_1_1_raw_user_data_wrapper.html',1,'ug::bridge::lua']]],
  ['rayelemintersectionrecord_19316',['RayElemIntersectionRecord',['../structug_1_1_ray_elem_intersection_record.html',1,'ug']]],
  ['record_19317',['Record',['../structug_1_1impl_1_1_project_vertices_to_close_edges_1_1_record.html',1,'ug::impl::ProjectVerticesToCloseEdges']]],
  ['reduce_5ftraits_19318',['reduce_traits',['../structpcl_1_1reduce__traits.html',1,'pcl']]],
  ['reduce_5ftraits_3c_20double_20_3e_19319',['reduce_traits&lt; double &gt;',['../structpcl_1_1reduce__traits_3_01double_01_4.html',1,'pcl']]],
  ['reduce_5ftraits_3c_20float_20_3e_19320',['reduce_traits&lt; float &gt;',['../structpcl_1_1reduce__traits_3_01float_01_4.html',1,'pcl']]],
  ['reducer_19321',['Reducer',['../classpcl_1_1_reducer.html',1,'pcl']]],
  ['reference_5felement_5ftraits_19322',['reference_element_traits',['../structug_1_1reference__element__traits.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20constrainededge_20_3e_19323',['reference_element_traits&lt; ConstrainedEdge &gt;',['../structug_1_1reference__element__traits_3_01_constrained_edge_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20constrainedquadrilateral_20_3e_19324',['reference_element_traits&lt; ConstrainedQuadrilateral &gt;',['../structug_1_1reference__element__traits_3_01_constrained_quadrilateral_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20constrainedtriangle_20_3e_19325',['reference_element_traits&lt; ConstrainedTriangle &gt;',['../structug_1_1reference__element__traits_3_01_constrained_triangle_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20constrainedvertex_20_3e_19326',['reference_element_traits&lt; ConstrainedVertex &gt;',['../structug_1_1reference__element__traits_3_01_constrained_vertex_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20constrainingedge_20_3e_19327',['reference_element_traits&lt; ConstrainingEdge &gt;',['../structug_1_1reference__element__traits_3_01_constraining_edge_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20constrainingquadrilateral_20_3e_19328',['reference_element_traits&lt; ConstrainingQuadrilateral &gt;',['../structug_1_1reference__element__traits_3_01_constraining_quadrilateral_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20constrainingtriangle_20_3e_19329',['reference_element_traits&lt; ConstrainingTriangle &gt;',['../structug_1_1reference__element__traits_3_01_constraining_triangle_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20edge_20_3e_19330',['reference_element_traits&lt; Edge &gt;',['../structug_1_1reference__element__traits_3_01_edge_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20hexahedron_20_3e_19331',['reference_element_traits&lt; Hexahedron &gt;',['../structug_1_1reference__element__traits_3_01_hexahedron_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20octahedron_20_3e_19332',['reference_element_traits&lt; Octahedron &gt;',['../structug_1_1reference__element__traits_3_01_octahedron_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20prism_20_3e_19333',['reference_element_traits&lt; Prism &gt;',['../structug_1_1reference__element__traits_3_01_prism_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20pyramid_20_3e_19334',['reference_element_traits&lt; Pyramid &gt;',['../structug_1_1reference__element__traits_3_01_pyramid_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20quadrilateral_20_3e_19335',['reference_element_traits&lt; Quadrilateral &gt;',['../structug_1_1reference__element__traits_3_01_quadrilateral_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20regularedge_20_3e_19336',['reference_element_traits&lt; RegularEdge &gt;',['../structug_1_1reference__element__traits_3_01_regular_edge_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20regularvertex_20_3e_19337',['reference_element_traits&lt; RegularVertex &gt;',['../structug_1_1reference__element__traits_3_01_regular_vertex_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20tetrahedron_20_3e_19338',['reference_element_traits&lt; Tetrahedron &gt;',['../structug_1_1reference__element__traits_3_01_tetrahedron_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20triangle_20_3e_19339',['reference_element_traits&lt; Triangle &gt;',['../structug_1_1reference__element__traits_3_01_triangle_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20vertex_20_3e_19340',['reference_element_traits&lt; Vertex &gt;',['../structug_1_1reference__element__traits_3_01_vertex_01_4.html',1,'ug']]],
  ['referenceedge_19341',['ReferenceEdge',['../classug_1_1_reference_edge.html',1,'ug']]],
  ['referenceelement_19342',['ReferenceElement',['../classug_1_1_reference_element.html',1,'ug']]],
  ['referenceelementprovider_19343',['ReferenceElementProvider',['../classug_1_1_reference_element_provider.html',1,'ug']]],
  ['referencehexahedron_19344',['ReferenceHexahedron',['../classug_1_1_reference_hexahedron.html',1,'ug']]],
  ['referencemapping_19345',['ReferenceMapping',['../classug_1_1_reference_mapping.html',1,'ug']]],
  ['referencemapping_3c_20ref_5felem_5ftype_2c_20worlddim_20_3e_19346',['ReferenceMapping&lt; ref_elem_type, worldDim &gt;',['../classug_1_1_reference_mapping.html',1,'ug']]],
  ['referencemapping_3c_20referenceedge_2c_20tworlddim_20_3e_19347',['ReferenceMapping&lt; ReferenceEdge, TWorldDim &gt;',['../classug_1_1_reference_mapping_3_01_reference_edge_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemapping_3c_20referencehexahedron_2c_20tworlddim_20_3e_19348',['ReferenceMapping&lt; ReferenceHexahedron, TWorldDim &gt;',['../classug_1_1_reference_mapping_3_01_reference_hexahedron_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemapping_3c_20referenceoctahedron_2c_20tworlddim_20_3e_19349',['ReferenceMapping&lt; ReferenceOctahedron, TWorldDim &gt;',['../classug_1_1_reference_mapping_3_01_reference_octahedron_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemapping_3c_20referenceprism_2c_20tworlddim_20_3e_19350',['ReferenceMapping&lt; ReferencePrism, TWorldDim &gt;',['../classug_1_1_reference_mapping_3_01_reference_prism_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemapping_3c_20referencepyramid_2c_20tworlddim_20_3e_19351',['ReferenceMapping&lt; ReferencePyramid, TWorldDim &gt;',['../classug_1_1_reference_mapping_3_01_reference_pyramid_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemapping_3c_20referencequadrilateral_2c_20tworlddim_20_3e_19352',['ReferenceMapping&lt; ReferenceQuadrilateral, TWorldDim &gt;',['../classug_1_1_reference_mapping_3_01_reference_quadrilateral_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemapping_3c_20referencetetrahedron_2c_20tworlddim_20_3e_19353',['ReferenceMapping&lt; ReferenceTetrahedron, TWorldDim &gt;',['../classug_1_1_reference_mapping_3_01_reference_tetrahedron_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemapping_3c_20referencetriangle_2c_20tworlddim_20_3e_19354',['ReferenceMapping&lt; ReferenceTriangle, TWorldDim &gt;',['../classug_1_1_reference_mapping_3_01_reference_triangle_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemapping_3c_20referencevertex_2c_20tworlddim_20_3e_19355',['ReferenceMapping&lt; ReferenceVertex, TWorldDim &gt;',['../classug_1_1_reference_mapping_3_01_reference_vertex_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemappingprovider_19356',['ReferenceMappingProvider',['../classug_1_1_reference_mapping_provider.html',1,'ug']]],
  ['referenceoctahedron_19357',['ReferenceOctahedron',['../classug_1_1_reference_octahedron.html',1,'ug']]],
  ['referenceprism_19358',['ReferencePrism',['../classug_1_1_reference_prism.html',1,'ug']]],
  ['referencepyramid_19359',['ReferencePyramid',['../classug_1_1_reference_pyramid.html',1,'ug']]],
  ['referencequadrilateral_19360',['ReferenceQuadrilateral',['../classug_1_1_reference_quadrilateral.html',1,'ug']]],
  ['referencetetrahedron_19361',['ReferenceTetrahedron',['../classug_1_1_reference_tetrahedron.html',1,'ug']]],
  ['referencetriangle_19362',['ReferenceTriangle',['../classug_1_1_reference_triangle.html',1,'ug']]],
  ['referencevertex_19363',['ReferenceVertex',['../classug_1_1_reference_vertex.html',1,'ug']]],
  ['refinementprojector_19364',['RefinementProjector',['../classug_1_1_refinement_projector.html',1,'ug']]],
  ['regalgebra_19365',['RegAlgebra',['../structug_1_1bridge_1_1_register_domain_algebra_dependent_1_1_reg_algebra.html',1,'ug::bridge::RegisterDomainAlgebraDependent']]],
  ['regend_19366',['RegEnd',['../structug_1_1bridge_1_1_algebra_type_i_d_provider_1_1_register_algebra_indices_1_1_reg_end.html',1,'ug::bridge::AlgebraTypeIDProvider::RegisterAlgebraIndices&lt; List &gt;::RegEnd'],['../structug_1_1bridge_1_1_register_algebra_dependent_1_1_reg_end.html',1,'ug::bridge::RegisterAlgebraDependent&lt; Functionality, List &gt;::RegEnd'],['../structug_1_1bridge_1_1_register_domain_algebra_dependent_1_1_reg_end.html',1,'ug::bridge::RegisterDomainAlgebraDependent&lt; Functionality, DomainList, AlgebraList &gt;::RegEnd'],['../structug_1_1bridge_1_1_register_domain_dependent_1_1_reg_end.html',1,'ug::bridge::RegisterDomainDependent&lt; Functionality, List &gt;::RegEnd'],['../structug_1_1_f_v1_inner_boundary_elem_disc_1_1_register_prep_timestep_1_1_reg_end.html',1,'ug::FV1InnerBoundaryElemDisc&lt; TImpl, TDomain &gt;::RegisterPrepTimestep&lt; List &gt;::RegEnd']]],
  ['region_19367',['Region',['../../plugins/structug_1_1_navier_stokes_1_1_region.html',1,'ug::NavierStokes']]],
  ['register_5fas_5fobserver_19368',['register_as_observer',['../structug_1_1_copy_attachment_handler_1_1register__as__observer.html',1,'ug::CopyAttachmentHandler']]],
  ['register_5fas_5fobserver_3c_20edge_2c_20dummy_20_3e_19369',['register_as_observer&lt; Edge, Dummy &gt;',['../structug_1_1_copy_attachment_handler_1_1register__as__observer_3_01_edge_00_01_dummy_01_4.html',1,'ug::CopyAttachmentHandler']]],
  ['register_5fas_5fobserver_3c_20face_2c_20dummy_20_3e_19370',['register_as_observer&lt; Face, Dummy &gt;',['../structug_1_1_copy_attachment_handler_1_1register__as__observer_3_01_face_00_01_dummy_01_4.html',1,'ug::CopyAttachmentHandler']]],
  ['register_5fas_5fobserver_3c_20vertex_2c_20dummy_20_3e_19371',['register_as_observer&lt; Vertex, Dummy &gt;',['../structug_1_1_copy_attachment_handler_1_1register__as__observer_3_01_vertex_00_01_dummy_01_4.html',1,'ug::CopyAttachmentHandler']]],
  ['register_5fas_5fobserver_3c_20volume_2c_20dummy_20_3e_19372',['register_as_observer&lt; Volume, Dummy &gt;',['../structug_1_1_copy_attachment_handler_1_1register__as__observer_3_01_volume_00_01_dummy_01_4.html',1,'ug::CopyAttachmentHandler']]],
  ['registeralgebradependent_19373',['RegisterAlgebraDependent',['../structug_1_1bridge_1_1_register_algebra_dependent.html',1,'ug::bridge']]],
  ['registeralgebraindices_19374',['RegisterAlgebraIndices',['../structug_1_1bridge_1_1_algebra_type_i_d_provider_1_1_register_algebra_indices.html',1,'ug::bridge::AlgebraTypeIDProvider']]],
  ['registerassemblingfuncs_19375',['RegisterAssemblingFuncs',['../structug_1_1_f_v1_inner_boundary_elem_disc_1_1_register_assembling_funcs.html',1,'ug::FV1InnerBoundaryElemDisc']]],
  ['registerdomain1dalgebradependent_19376',['RegisterDomain1dAlgebraDependent',['../structug_1_1bridge_1_1_register_domain1d_algebra_dependent.html',1,'ug::bridge']]],
  ['registerdomain2d3dalgebradependent_19377',['RegisterDomain2d3dAlgebraDependent',['../structug_1_1bridge_1_1_register_domain2d3d_algebra_dependent.html',1,'ug::bridge']]],
  ['registerdomain2dalgebradependent_19378',['RegisterDomain2dAlgebraDependent',['../structug_1_1bridge_1_1_register_domain2d_algebra_dependent.html',1,'ug::bridge']]],
  ['registerdomain3dalgebradependent_19379',['RegisterDomain3dAlgebraDependent',['../structug_1_1bridge_1_1_register_domain3d_algebra_dependent.html',1,'ug::bridge']]],
  ['registerdomainalgebradependent_19380',['RegisterDomainAlgebraDependent',['../structug_1_1bridge_1_1_register_domain_algebra_dependent.html',1,'ug::bridge']]],
  ['registerdomaindependent_19381',['RegisterDomainDependent',['../structug_1_1bridge_1_1_register_domain_dependent.html',1,'ug::bridge']]],
  ['registerelemfunc_19382',['RegisterElemFunc',['../structug_1_1_convection_shapes_full_upwind_1_1_register_elem_func.html',1,'ug::ConvectionShapesFullUpwind&lt; TDim &gt;::RegisterElemFunc'],['../structug_1_1_convection_shapes_no_upwind_1_1_register_elem_func.html',1,'ug::ConvectionShapesNoUpwind&lt; TDim &gt;::RegisterElemFunc'],['../structug_1_1_convection_shapes_partial_upwind_1_1_register_elem_func.html',1,'ug::ConvectionShapesPartialUpwind&lt; TDim &gt;::RegisterElemFunc'],['../structug_1_1_convection_shapes_weighted_upwind_1_1_register_elem_func.html',1,'ug::ConvectionShapesWeightedUpwind&lt; TDim &gt;::RegisterElemFunc']]],
  ['registerfv1_19383',['RegisterFV1',['../../plugins/structug_1_1_navier_stokes_1_1_navier_stokes_sym_b_c_f_v1_1_1_register_f_v1.html',1,'ug::NavierStokes::NavierStokesSymBCFV1']]],
  ['registerlocaldiscr_19384',['RegisterLocalDiscr',['../../plugins/structug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_fract_f_v1_1_1_register_local_discr.html',1,'ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1&lt; class &gt;::RegisterLocalDiscr'],['../../plugins/structug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_f_v1_1_1_register_local_discr.html',1,'ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1&lt; class &gt;::RegisterLocalDiscr'],['../../plugins/structug_1_1_electromagnetism_1_1_eddy_current___e___nedelec_1_1_register_local_discr.html',1,'ug::Electromagnetism::EddyCurrent_E_Nedelec&lt; class, class &gt;::RegisterLocalDiscr'],['../../plugins/structug_1_1_electromagnetism_1_1_nedelec_loop_current_1_1_aux_laplace_loc_ass_1_1_register_local_discr.html',1,'ug::Electromagnetism::NedelecLoopCurrent::AuxLaplaceLocAss::RegisterLocalDiscr'],['../../plugins/structug_1_1_electromagnetism_1_1_nedelec_project_1_1_aux_laplace_loc_ass_1_1_register_local_discr.html',1,'ug::Electromagnetism::NedelecProject::AuxLaplaceLocAss::RegisterLocalDiscr']]],
  ['registerpreptimestep_19385',['RegisterPrepTimestep',['../structug_1_1_f_v1_inner_boundary_elem_disc_1_1_register_prep_timestep.html',1,'ug::FV1InnerBoundaryElemDisc']]],
  ['registerrefdimfunc_19386',['RegisterRefDimFunc',['../structug_1_1_convection_shapes_full_upwind_1_1_register_ref_dim_func.html',1,'ug::ConvectionShapesFullUpwind&lt; TDim &gt;::RegisterRefDimFunc'],['../structug_1_1_convection_shapes_no_upwind_1_1_register_ref_dim_func.html',1,'ug::ConvectionShapesNoUpwind&lt; TDim &gt;::RegisterRefDimFunc'],['../structug_1_1_convection_shapes_partial_upwind_1_1_register_ref_dim_func.html',1,'ug::ConvectionShapesPartialUpwind&lt; TDim &gt;::RegisterRefDimFunc'],['../structug_1_1_convection_shapes_weighted_upwind_1_1_register_ref_dim_func.html',1,'ug::ConvectionShapesWeightedUpwind&lt; TDim &gt;::RegisterRefDimFunc']]],
  ['registertypepairfunctor_19387',['RegisterTypePairFunctor',['../structug_1_1detail_1_1_register_type_pair_functor.html',1,'ug::detail']]],
  ['registry_19388',['Registry',['../classug_1_1bridge_1_1_registry.html',1,'ug::bridge']]],
  ['regnext_19389',['RegNext',['../structug_1_1bridge_1_1_algebra_type_i_d_provider_1_1_register_algebra_indices_1_1_reg_next.html',1,'ug::bridge::AlgebraTypeIDProvider::RegisterAlgebraIndices&lt; List &gt;::RegNext'],['../structug_1_1bridge_1_1_register_algebra_dependent_1_1_reg_next.html',1,'ug::bridge::RegisterAlgebraDependent&lt; Functionality, List &gt;::RegNext'],['../structug_1_1bridge_1_1_register_domain_dependent_1_1_reg_next.html',1,'ug::bridge::RegisterDomainDependent&lt; Functionality, List &gt;::RegNext'],['../structug_1_1_f_v1_inner_boundary_elem_disc_1_1_register_prep_timestep_1_1_reg_next.html',1,'ug::FV1InnerBoundaryElemDisc&lt; TImpl, TDomain &gt;::RegisterPrepTimestep&lt; List &gt;::RegNext']]],
  ['regnextdomain_19390',['RegNextDomain',['../structug_1_1bridge_1_1_register_domain_algebra_dependent_1_1_reg_next_domain.html',1,'ug::bridge::RegisterDomainAlgebraDependent']]],
  ['regnextdomainalgebra_19391',['RegNextDomainAlgebra',['../structug_1_1bridge_1_1_register_domain_algebra_dependent_1_1_reg_next_domain_algebra.html',1,'ug::bridge::RegisterDomainAlgebraDependent']]],
  ['regularedge_19392',['RegularEdge',['../classug_1_1_regular_edge.html',1,'ug']]],
  ['regularvertex_19393',['RegularVertex',['../classug_1_1_regular_vertex.html',1,'ug']]],
  ['relativedensityupdater_19394',['RelativeDensityUpdater',['../../plugins/classug_1_1_small_strain_mechanics_1_1_relative_density_updater.html',1,'ug::SmallStrainMechanics']]],
  ['repeatedcol_19395',['RepeatedCol',['../structug_1_1_string_table_stream_1_1_repeated_col.html',1,'ug::StringTableStream']]],
  ['reservablearray2_19396',['ReservableArray2',['../classug_1_1_reservable_array2.html',1,'ug']]],
  ['revisioncounter_19397',['RevisionCounter',['../classug_1_1_revision_counter.html',1,'ug']]],
  ['riverordering_19398',['RiverOrdering',['../classug_1_1_river_ordering.html',1,'ug']]],
  ['rotatingcone2d_19399',['RotatingCone2d',['../classug_1_1_rotating_cone2d.html',1,'ug']]],
  ['rotatingvelocity2d_19400',['RotatingVelocity2d',['../classug_1_1_rotating_velocity2d.html',1,'ug']]],
  ['row_5fiterator_19401',['row_iterator',['../class_scalar_matrix_adapter_1_1row__iterator.html',1,'ScalarMatrixAdapter&lt; AT, ST &gt;::row_iterator'],['../class_scalar_sub_matrix_adapter_1_1row__iterator.html',1,'ScalarSubMatrixAdapter&lt; AT, ST, R, C &gt;::row_iterator'],['../classug_1_1_g_p_u_sparse_matrix_1_1row__iterator.html',1,'ug::GPUSparseMatrix&lt; TValueType &gt;::row_iterator'],['../classug_1_1_map_sparse_matrix_1_1row__iterator.html',1,'ug::MapSparseMatrix&lt; TValueType &gt;::row_iterator'],['../classug_1_1_sparse_matrix_1_1row__iterator.html',1,'ug::SparseMatrix&lt; TValueType &gt;::row_iterator']]],
  ['rowsendingscheme_19402',['RowSendingScheme',['../classug_1_1_row_sending_scheme.html',1,'ug']]]
];
