name: UG4 Doxygen Documentation

on:
  repository_dispatch:
    types:
      - trigger-doxygen

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: docs

      - name: Checkout ugcore
        uses: actions/checkout@v3
        with:
          repository: UG4/ugcore
          path: ugcore

      - name: Install Doxygen
        run: |
          sudo apt-get install doxygen

      - name: Generate Docs
        working-directory: ugcore/docs
        run: |
          sudo bash generate_amalgamated_docu.sh doxylog.log 1

      - name: Copy Docs
        run: |
          sudo \cp -rf ugcore/docs/ug4/html/* docs/

      - name: Commit and Push Docs
        working-directory: docs
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Documentation"
          git push
